### ISSUE TITLE
<api> Couldn't dispose a session

### ISSUE THREAD

**Issue by kug4586** [AIIA-GCU/meta-gachon-app#5]
I want to clear a session when app kill. So I use AppLifecycleListener in "first" widget of app. I distinguished the state of killing app between Android and iOS. How to resolve this problem?

**Comment by hyunbridge** [comment]
앱이 종료 때 세션 쿠키를 삭제하기를 원하시는 건가요?

**Comment by kug4586** [comment]
얍

**Comment by hyunbridge** [comment]
지금은 API 응답에 있는 세션 쿠키를 SharedPreferences에 저장해서 앱이 닫혀도 세션이 유지되는 건데 세션을 유지하지 않으려 한다면 그걸 스태틱 변수 만들어서 저장하면 될 것 같아요~
근데 굳이 앱이 닫힐때 세션을 만료시키는 이유가 있나요? 그럼 켤때마다 로그인 해야 하지 않나요

**Comment by hyunbridge** [comment]
아니면 API 클라이언트에서 분기문을 만들어서 서버에서 401 오류가 날아오면 세션을 정리하고 로그인 페이지로 이동시켜도 괜찮을 것 같아요
세션을 자동으로 정리하고 등록된onSessionDispose 리스너 함수를 콜하도록 API 클라이언트를 수정하면 될 것 같은데, 어떻게 생각하시나요

**Comment by kug4586** [comment]
좋을 것 같네요! 한번 시도해볼게
